SELECT *

FROM TB_MODELO_MOD MOD_ 

INNER JOIN TB_MARCA_MAR MAR
  
ON MAR.MAR_CODIGO = MOD_.MAR_CODIGO

WHERE MAR_DESCRICAO IN ('AUDI','PORSCHE')


SELECT  /* SELECIONAR  SUA DESCRIÇÃO DO CARRO E PESQUISAR  MODELO */

MAR_DESCRICAO, COUNT(*)

FROM TB_MODELO_MOD MOD_
INNER JOIN TB_MARCA_MAR MAR
  ON MAR.MAR_CODIGO = MOD_.MAR_CODIGO
      GROUP BY MAR_DESCRICAO


INSERT INTO TB_CLIENTE_CLI
(CLI_CPF,CLI_NOME,CLI_DATA_NASC,CLI_SEXO,CLI_EMAIL,CLI_ENDERECO,CLI_NUMERO, CLI_COMPLEMENTO,CLI_BAIRRO,CLI_CEP,USU_CODIGO,CID_CODIGO) VALUES
('45495796845','BRUNO FELIX DE SOUZA','1995-03-05','M', 'BRUNO.FELIX.SOUSA@HOTMAIL.COM',
 'RUA JOAO MARIA DA SILVA','147','FUNDOS','JARDIM DOS PRADOS','04679-160',1,5370)

 
 SELECT * 
 FROM TB_CLIENTE_CLI CLI
 INNER JOIN TB_CIDADE_CID CID
   ON CID.CID_CODIGO = CLI.CID_CODIGO

   INNER JOIN TB_ESTADO_EST EST
  ON  EST.EST_CODIGO =CID.EST_CODIGO

  INNER JOIN TB_USUARIO_USU USU
   ON CLI.USU_CODIGO = USU.USU_CODIGO


   INSERT INTO TB_VEICULO_VEI
   (VEI_PLACA,VEI_CHASSI,VEI_ANO_FABRICACAO,VEI_COR,MOD_CODIGO,CLI_CODIGO) VALUES
   ('FAZ6749','1234567890',2014,'PRATA',535,1),
   ('BRI4772','09876542321',2008,'PRATA',154,1)
   

   INSERT INTO TB_TELEFONE_TEL
   (TEL_DDD,TEL_NUMERO,TTT_CODIGO,CLI_CODIGO,USU_CODIGO) VALUES
   ('11','952227876',3,1,1),
   ('11','39768359' ,1,1,1),
   ('11','2980-5500',2,1,1)

   SELECT * 

   FROM TB_CLIENTE_CLI CLI
    INNER JOIN TB_VEICULO_VEI VEI
	 ON VEI.CLI_CODIGO =CLI.CLI_CODIGO

	 INNER JOIN TB_MODELO_MOD MOD_
     ON  VEI.MOD_CODIGO  = MOD_.MOD_CODIGO

	 INNER JOIN TB_MARCA_MAR  MAR
	 ON MOD_.MAR_CODIGO = MAR.MAR_CODIGO





