SELECT *

FROM TB_CLIENTE_CLI CLI
    INNER JOIN TB_VEICULO_VEI VEI
	 ON VEI.CLI_CODIGO =CLI.CLI_CODIGO

	INNER JOIN TB_VEICULO_COMBUSTIVEL_TVC TVC
	ON VEI.VEI_CODIGO = TVC.VEI_CODIGO

	INNER JOIN TB_MODELO_MOD MOD_
    ON  VEI.MOD_CODIGO  = MOD_.MOD_CODIGO

	INNER JOIN TB_MARCA_MAR  MAR
	ON MOD_.MAR_CODIGO = MAR.MAR_CODIGO

    LEFT JOIN TB_COMBUSTIVEL_COM COM
	ON COM.COM_CODIGO =  TVC.TVC_CODIGO
