INSERT INTO TB_USUARIO_USU
(USU_NOME, USU_LOGIN, USU_SENHA, USU_ATIVO)
VALUES
('Angela Moreira Dos Santos Camargo','Angela.Camargo','senac@33',1),
('Eduarda Leobet','Eduarda.Leobet','senac@14',1),
('Flaviana Gaspar','Flaviana.Gaspar','senac@15',1),
('Geovana Brambatti Vanzin','Geovana.Vanzin','senac@24',1),
('Marcela Manenti Pozzo','Marcela.Pozzo','senac@21',1),
('Rodrigo Da Silva Oliboni','Rodrigo.Oliboni','senac@24',1),
('Juliano Pereira Da Silva','Juliano.Silva','senac@24',1),
('Jorge Luis Moraes Franklin','Jorge.Franklin','senac@26',1),
('Airton Luiz Gudi','Airton.Gudi','senac@16',1),
('Ana Keila Moreira De Lima','Ana.Lima','senac@25',1),
('Josiane Bastos De Morais','Josiane.Morais','senac@24',1),
('Mariana Silva Branco','Mariana.Branco','senac@20',1),
('Patricia Formento','Patricia.Formento','senac@17',1),
('Philipp Duarte','Philipp.Duarte','senac@14',1),
('Renata Zomer','Renata.Zomer','senac@12',1),
('Alessandra Ferreira Da Silva','Alessandra.Silva','senac@28',1),
('Anderson Luiz Ramos','Anderson.Ramos','senac@19',1),
('Andre Carelli','Andre.Carelli','senac@13',1),
('Ariel Ramos Rosa Farias','Ariel.Farias','senac@23',1),
('Camila Palma Tedesco','Camila.Tedesco','senac@20',1),
('Cristiane Aparecida Chiquetti','Cristiane.Chiquetti','senac@29',1),
('Cristina Camila Marques','Cristina.Marques','senac@23',1),
('Daniella Marques','Daniella.Marques','senac@16',1),
('Diego Jose Stringhini','Diego.Stringhini','senac@21',1),
('Edmilson Freitag Terres','Edmilson.Terres','senac@23',1),
('Eduardo Hilário Sá','Eduardo.Sá','senac@18',1),
('Elisete Terezinha Schneck','Elisete.Schneck','senac@25',1)
