INSERT INTO TB_COMBUSTIVEL_COM (COM_DESCRICAO) VALUES 
('GASOLINA'),
('ALCOOL'),
('GNV'),
('DIESEL')

INSERT INTO TB_FORMA_PAGTO_TFP (TFP_DESCRICAO) VALUES
('DINHEIRO'),
('CHEQUE'),
('CARTÃO DE CRÉDITO'),
('CARTÃO DE DÉBITO')

INSERT INTO TB_TIPO_TELEFONE_TTT (TTT_DESCRICAO) VALUES
('RESIDENCIAL'),
('COMERCIAL'),
('CELULAR'),
('RECADO')

