INSERT INTO TB_CLIENTE_CLI
(CLI_CPF, CLI_NOME, CLI_DATA_NASC, CLI_SEXO, 
CLI_EMAIL,
CLI_ENDERECO, CLI_NUMERO, CLI_COMPLEMENTO, CLI_BAIRRO,
CLI_CEP, USU_CODIGO, CID_CODIGO) VALUES 
('15122132844','Estevam Michael Ferraz Campos','1975-05-23','M',
'estevam.mfcampos@sp.senac.br',
'Rua Agostinho Correa','141','Bloco 6 - Apto 403','Vila Regina',
'02968-090', 1, 5370)

INSERT INTO TB_VEICULO_VEI 
(VEI_PLACA, VEI_CHASSI, VEI_ANO_FABRICACAO,
VEI_COR, MOD_CODIGO, CLI_CODIGO) VALUES 
('FAZ6749','1234567890', 2014,'PRATA',538,1),
('BRI4772','0987654321', 2008,'PRATA',154,1)

INSERT INTO TB_TELEFONE_TEL
(TEL_DDD, TEL_NUMERO, TTT_CODIGO, CLI_CODIGO, USU_CODIGO)
VALUES
('11', '982227876',3,1,1),
('11', '39768359',1,1,1),
('11', '2980-5500',2,1,1)

SELECT * FROM TB_VEICULO_COMBUSTIVEL_TVC
SELECT * FROM TB_COMBUSTIVEL_COM
SELECT * FROM TB_VEICULO_VEI

INSERT INTO TB_VEICULO_COMBUSTIVEL_TVC
(VEI_CODIGO, COM_CODIGO)
VALUES (1,1),(1,2),(2,1),(2,1)

SELECT 
	CLI_NOME,
	MOD_DESCRICAO, 
	COM_DESCRICAO,
	CID_CIDADE,
	EST_ESTADO
FROM TB_VEICULO_VEI VEI
INNER JOIN TB_MODELO_MOD MOD_				ON MOD_.MOD_CODIGO = VEI.MOD_CODIGO
INNER JOIN TB_VEICULO_COMBUSTIVEL_TVC TVC	ON VEI.VEI_CODIGO = TVC.VEI_CODIGO
INNER JOIN TB_COMBUSTIVEL_COM COM			ON COM.COM_CODIGO = TVC.COM_CODIGO
INNER JOIN TB_CLIENTE_CLI CLI				ON CLI.CLI_CODIGO = VEI.CLI_CODIGO
INNER JOIN TB_CIDADE_CID CID				ON CID.CID_CODIGO = CLI.CID_CODIGO
INNER JOIN TB_ESTADO_EST EST				ON EST.EST_CODIGO = CID.EST_CODIGO


