 SELECT  CLI_NOME,MOD_DESCRICAO,COM_DESCRICAO,CID_CIDADE,EST_ESTADO
 
	
	
	FROM TB_VEICULO_VEI VEI
	INNER JOIN TB_VEICULO_COMBUSTIVEL_TVC TVC
	ON TVC.VEI_CODIGO = VEI.VEI_CODIGO
	
	INNER JOIN TB_MODELO_MOD MOD_
	ON VEI.VEI_CODIGO = TVC.TVC_CODIGO

	INNER JOIN TB_COMBUSTIVEL_COM
    ON VEI.VEI_CODIGO = TVC.VEI_CODIGO

	INNER JOIN TB_CLIENTE_CLI CLI
	 ON VEI.VEI_CODIGO = CLI.CLI_CODIGO

	 INNER JOIN TB_CIDADE_CID CID
	 ON CLI.CID_CODIGO = CID.CID_CODIGO

	 INNER JOIN TB_ESTADO_EST EST
	 ON CID.EST_CODIGO = EST.EST_CODIGO



     