SELECT *
FROM TB_PRODUTO_ORDEM_SERVICO_POS

SELECT *
FROM TB_ORDEM_SERVICO_ORD

SELECT *
FROM TB_ORCAMENTO_ORC

SELECT *
FROM TB_USUARIO_USU

SELECT *
FROM TB_PRODUTO_SERVICO_TPS


INSERT INTO TB_ORDEM_SERVICO_ORD
(ORD_DATA, ORD_VALOR, ORC_CODIGO, USU_CODIGO)
VALUES
('2016-03-23', 2244.68, 1, 6)

INSERT INTO TB_PRODUTO_ORDEM_SERVICO_POS
(POS_QTDE, POS_VALOR, ORD_CODIGO, TPS_CODIGO)
VALUES
(4, 473.67,1,2),
(1, 150.00, 1, 9),
(4, 50.00, 1, 10)

INSERT INTO 