
SELECT*

FROM TB_USUARIO_USU
WHERE EST_ESTADO = 'MG'

DELETE USU_
 

INSERT INTO TB_USUARIO_USU
(USU_NOME, USU_LOGIN, USU_SENHA, USU_ATIVO)
VALUES
('Jeferson Ganda','Jeferson.ganda','senac@123',0)
