SELECT * FROM TB_MOVIMENTACAO_MOV


SELECT 

ORC.ORC_DATA,ORC.ORC_VALOR,MOV_DATA_INICIO,MOV_DATA_TERMINO,
USU_NOME,VEI_PLACA,MOD_DESCRICAO, MAR_DESCRICAO
CLI_NOME, CID_CIDADE, EST_ESTADO

FROM  TB_MOVIMENTACAO_MOV MOV

INNER JOIN TB_ORCAMENTO_ORC ORC 
ON ORC.ORC_CODIGO = MOV.ORC_CODIGO

INNER JOIN TB_USUARIO_USU USU
ON USU.USU_CODIGO = MOV.USU_CODIGO

INNER JOIN TB_VEICULO_VEI VEI
ON VEI.VEI_CODIGO= ORC.VEI_CODIGO

INNER JOIN TB_MODELO_MOD MOD_
ON MOD_.MOD_CODIGO = VEI.MOD_CODIGO

INNER JOIN TB_MARCA_MAR MAR
ON MAR.MAR_CODIGO = MOD_.MAR_CODIGO 

INNER JOIN TB_CLIENTE_CLI CLI 
ON CLI.CLI_CODIGO = VEI.VEI_CODIGO 

INNER JOIN TB_CIDADE_CID CID
ON CLI.CID_CODIGO = CID.CID_CODIGO

INNER JOIN TB_ESTADO_EST EST
ON CID.EST_CODIGO = EST.EST_CODIGO




SELECT ORC.ORC_CODIGO,ORD_DATA, ORC.ORC_DATA,MOV_DATA_INICIO,MOV_DATA_TERMINO, USU_NOME, TPS_DESCRICAO

FROM   TB_ORDEM_SERVICO_ORD ORD



INNER JOIN TB_ORCAMENTO_ORC ORC ON ORC.ORC_CODIGO = ORD.ORC_CODIGO

INNER JOIN TB_MOVIMENTACAO_MOV MOV ON MOV.ORD_CODIGO = ORD.ORD_CODIGO	

LEFT JOIN TB_PRODUTO_ORDEM_SERVICO_POS POS ON MOV.POS_CODIGO = POS.POS_CODIGO

LEFT JOIN TB_PRODUTO_SERVICO_TPS TPS ON POS.TPS_CODIGO = TPS.TPS_CODIGO

INNER JOIN TB_USUARIO_USU USU ON MOV.USU_CODIGO = USU.USU_CODIGO


WHERE ORC.ORC_CODIGO = 1



