


UPDATE TB_CLIENTE_CLI
SET
CLI_ENDERECO = 'RUA TUITO',
CLI_NUMERO = '54',
CLI_BAIRRO = 'LAPA',
CLI_CEP = '05052-000'

WHERE 

CLI_CODIGO = 1

DELETE FROM  TB_CLIENTE_CLI

WHERE

CLI_CODIGO = 1

SELECT * FROM TB_COMBUSTIVEL_COM

UPDATE TB_VEICULO_COMBUSTIVEL_TVC
SET COM_CODIGO = 2
WHERE TVC_CODIGO = 4


SELECT  CLI_NOME,MOD_DESCRICAO,COM_DESCRICAO,CID_CIDADE,EST_ESTADO
 
	
	
	FROM TB_VEICULO_VEI VEI
	INNER JOIN TB_VEICULO_COMBUSTIVEL_TVC TVC
	ON TVC.VEI_CODIGO = VEI.VEI_CODIGO
	
	INNER JOIN TB_MODELO_MOD MOD_
	ON VEI.MOD_CODIGO = MOD_.MOD_CODIGO

	INNER JOIN TB_COMBUSTIVEL_COM COM
    ON COM.COM_CODIGO= TVC.COM_CODIGO

	INNER JOIN TB_CLIENTE_CLI CLI
	 ON VEI.VEI_CODIGO = CLI.CLI_CODIGO

	 INNER JOIN TB_CIDADE_CID CID
	 ON CLI.CID_CODIGO = CID.CID_CODIGO

	 INNER JOIN TB_ESTADO_EST EST
	 ON CID.EST_CODIGO = EST.EST_CODIGO


     INSERT INTO TB_ORCAMENTO_ORC
	 (ORC_DATA, ORC_VALOR, VEI_CODIGO, USU_CODIGO)

	 VALUES

	 ('2016-03-22', 2244.68, 1,1),
	 ('2016-03-22', 1346.00, 2,1)


	 INSERT INTO TB_PRODUTO_ORCAMENTO_TPO
      
	(TPO_QTDE,TPO_VALOR,ORC_CODIGO, TPS_CODIGO)     /* INSERIR VALORES PARA A TABELA DE PRODUTOS_ORCAMENTOS, TEMOS QUE IR ATÉ A TABELA DE 
	PRODUTOS E ORCAMENTOS A QUAL JÁ FOI COLOCADA  OS VALORES NA TABELA,, OU SEJA QUANDO QUISER COLOCAR VALORES CONSULTAR PRIMEIRO QUAL É SEU
	CODIGO E SUA DESCRIÇÃO*/

	VALUES

	(4,473.67,1,2),
	(1,150,1,9),
	(4,50,1,10),
	(4,249,2,11),
	(1,150,2,9),
	(4,50,2,10)

	SELECT * FROM TB_PRODUTO_ORCAMENTO_TPO

	

  SELECT   ORC.ORC_CODIGO, ORC_DATA, ORC_VALOR, CLI_NOME, MOD_DESCRICAO, MAR_DESCRICAO, TPS_DESCRICAO, TPS_VALOR
  FROM    TB_VEICULO_VEI VEI
  


	INNER JOIN TB_MODELO_MOD MOD_
	ON VEI.MOD_CODIGO = MOD_.MOD_CODIGO

	INNER JOIN TB_MARCA_MAR MAR
	ON MAR.MAR_CODIGO = MOD_.MAR_CODIGO
	
	INNER JOIN TB_ORCAMENTO_ORC ORC
	ON  ORC.VEI_CODIGO = VEI.VEI_CODIGO

	INNER JOIN TB_PRODUTO_ORCAMENTO_TPO TPO
	ON TPO.ORC_CODIGO = ORC.ORC_CODIGO

	INNER JOIN TB_CLIENTE_CLI CLI
	ON VEI.CLI_CODIGO = CLI.CLI_CODIGO

	INNER JOIN TB_PRODUTO_SERVICO_TPS TPS
	ON TPS.TPS_CODIGO = TPO.TPS_CODIGO

	/* TRAZENDO INFORMAÇÕES, SOBRE OS RELACIONAMENTOS ENTRE O DER, USANDO I INNER JOIN, E COLOCANDO AS SEGUINTES INFORMÃÇÕES QUE ESTÃO A
	CIMA NO SELETE COLOCANDO OS RELACIONAMENTOS PARTINDO DA ENTIDADE VEICULO, /* 
	