select * 
from TB_CLIENTE_CLI

update TB_CLIENTE_CLI
set
CLI_ENDERECO = 'rua tito',
CLI_NUMERO = '54',
CLI_BAIRRO = 'lapa',
CLI_CEP = '05052-000',
CLI_NOME = 'jonathan',
CLI_COMPLEMENTO = '',
CLI_EMAIL = ''
where 
CLI_CODIGO = 1

delete 
from TB_VEICULO_COMBUSTIVEL_TVC
where TVC_CODIGO > 4

UPDATE TB_MOVIMENTACAO_MOV
SET MOV_DATA_INICIO = '03/14/2016 01:35PM'
WHERE MOV_CODIGO = 11
